### ISSUE TITLE
Sleepiq binding

### ISSUE THREAD

**Issue by brianwarner** [mhilbush/openhab-binding-releases#1]
Hey Mark, I've been using the updated SleepIQ binding with 3.3 and am updating to 3.4 today. Your changes have been rock solid. Have you contributed the updated version back to mainline?

Thanks again for doing this, it's let me create some pretty nice automations that weren't possible with the original version.

**Comment by mhilbush** [comment]
I'm planning to submit it shortly, after I finish up a couple things on my plate.

**Comment by brianwarner** [comment]
That's awesome, if there's anything I can help with, particularly testing, please let me know.

**Comment by mhilbush** [comment]
I submitted the PR today.

**Comment by brianwarner** [comment]
You rock, that's awesome. Looking forward to using it in mainline!
